apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: demo-app
  path: ./k8s/overlays/production
  prune: true
  wait: true
  timeout: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: demo-app
      namespace: demo-app
